$(function () {
  ;('use strict')
  let $container = $('.container')

  const spaces = (num) => {
    let divSpaces = ''
    for (var i = 1; i < num; i++) {
      divSpaces += `<div class="box border-none "></div>`
    }
    return divSpaces
  }

  const element = (num, elName, weight, color) => {
    return `<div class="box border ${color}"><p>${num}</p><h4>${elName}</h4><p>${weight}</p></div>`
  }
  const number = (num, margen) => {
    return `<div class='box border-none ${margen}'><h5>${num}</h5></div>`
  }

  // 0° LINE
  $container.append(`<div class="box "><h5>Group Period</h5></div>`)
  for (var i = 1; i < 19; i++) {
    $container.append(`<div class="box border-none"><h5>${i}</h5></div>`)
  }

  // 1° LINE
  $container.append(number('1', ''))
  $container.append(element('1', 'H', '1.008', 'cyan'))
  $container.append(spaces(17))
  $container.append(element('2', 'He', '4.0026', 'yellow'))
  // 2° LINE
  $container.append(number('2', ''))
  $container.append(element('3', 'Li', '6.94', 'cyan'))
  $container.append(element('4', 'Be', '9.0122', 'cyan'))
  $container.append(spaces(11))
  $container.append(element('5', 'B', '10.81', 'yellow'))
  $container.append(element('6', 'C', '12.011', 'yellow'))
  $container.append(element('7', 'N', '14.007', 'yellow'))
  $container.append(element('8', 'O', '15.999', 'yellow'))
  $container.append(element('9', 'F', '18.998', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  // 3° LINE
  $container.append(number('3', ''))
  $container.append(element('3', 'Li', '6.94', 'cyan'))
  $container.append(element('4', 'Be', '9.0122', 'cyan'))
  $container.append(spaces(11))
  $container.append(element('5', 'B', '10.81', 'yellow'))
  $container.append(element('6', 'C', '12.011', 'yellow'))
  $container.append(element('7', 'N', '14.007', 'yellow'))
  $container.append(element('8', 'O', '15.999', 'yellow'))
  $container.append(element('9', 'F', '18.998', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  // 4° LINE
  $container.append(number('4', ''))
  $container.append(element('11', 'Na', '22.990', 'cyan'))
  $container.append(element('12', 'Mg', '24.305', 'cyan'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  // 5° LINE
  $container.append(number('4', ''))
  $container.append(element('11', 'Na', '22.990', 'cyan'))
  $container.append(element('12', 'Mg', '24.305', 'cyan'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  // 6° LINE
  $container.append(number('4', ''))
  $container.append(element('11', 'Na', '22.990', 'cyan'))
  $container.append(element('12', 'Mg', '24.305', 'cyan'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  // 7° LINE
  $container.append(number('4', ''))
  $container.append(element('11', 'Na', '22.990', 'cyan'))
  $container.append(element('12', 'Mg', '24.305', 'cyan'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('12', 'Mg', '24.305', 'pink'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  $container.append(element('9', 'Ne', '20.180', 'yellow'))
  // 8° LINE
  $container.append(number('', 'mt-2'))
  $container.append(number('*Lanthanoids', 'mt-2'))
  $container.append(number('*', 'mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(element('9', 'Ne', '20.180', 'green mt-2'))
  $container.append(spaces(2))
  // 8° LINE
  $container.append(number('', ''))
  $container.append(number('', ''))
  $container.append(number('**Actinoid', ''))
  $container.append(number('**', ''))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(element('9', 'Ne', '20.180', 'green'))
  $container.append(spaces(4))
})
